# Generated by Django 5.1.1 on 2024-10-16 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oneoffmeetingtable',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='meeting_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oneoffmeetingtable',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
