# Generated by Django 5.1.1 on 2024-10-28 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='task_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
