# Generated by Django 5.1.1 on 2024-10-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_taskcategory_id_taskcategory_task_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
